### ISSUE TITLE
建立一个新的paracraft项目后无法进入该项目的世界

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#12]

**Comment by beyondliu** [comment]
建议创建Paracraft项目的时候，就跟客户端上创建项目一样，提供“超平坦”，“随机地形”，“空”几个选项，用户勾选后直接创立一个paracraft世界，用户点击后就可以启动客户端进入该世界。

**Comment by Sandu1213** [comment]
@azothli 宇哥，请评估规划一下

**Comment by azothli** [comment]
之前是实现有技术问题，所以是创建后，转到praacraft引导用户选择参数。
现在是 把这个行为转到用户的本地进行运算，都好了之后，上传形成在线世界。
这样调整的话，创建的运算需要服务器进行，可能改动会比较大。
初版的设计，我也希望实现远亮说的这个效果，还是请西峙评估下技术问题。
@LiXizhi
