### ISSUE TITLE
打开Keepwork Editor时，左上角的保存是保存所有的未保存文件吗？

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#13]
可能导致的问题是一个电脑上可能有多个文件未同步。点击这个保存按钮后服务器上所有的这几个文件都被覆盖了。不点击这个保存按钮又不知道是哪个文件未更新，需要更新。

**Comment by azothli** [comment]
不是，是当前文件

**Comment by beyondliu** [comment]
这个容我在家里的电脑上再试下。记得以前使用的时候有点奇怪的现象。

**Comment by beyondliu** [comment]
那如果有多个文件没有保存需要保存，怎么办呢？ctrl+s目前的实现也是只保存当前打开文件。

**Comment by beyondliu** [comment]
有没有同时保存多个文件的需求？比如编辑的文件比较多，或者有时候忘记了保存某个文件？建议关注一下这方面的用户行为，关注一段时间，摸准需求再看如何解决。

**Comment by azothli** [comment]
有这个功能，在文件目录树的已打开文件中
![image](https://user-images.githubusercontent.com/22001356/53784614-c796e780-3f50-11e9-874e-0b4c5a4e6f6c.png)

**Comment by beyondliu** [comment]
ok, 疏忽了。
