### ISSUE TITLE
Keepwork收藏项目

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#15]
好像keepwork不能浏览已经收藏的项目？

**Comment by azothli** [comment]
安排了计划，应该是本周的版本内容

**Comment by Sandu1213** [comment]
由#[3588](https://github.com/tatfook/keepwork/issues/3588)跟进，下个版本会更新

**Comment by Sandu1213** [comment]
收藏项目目前可以在个人主页->项目页进行查看了
