### ISSUE TITLE
keepwork首页的“大家都觉得赞”

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#18]
keepwork首页的“大家都觉得赞”是按什么排序的？感觉应该是按点赞的数量，但是却出现了几个点赞为0的在首页里，而有不少点赞为5，为2，为1的却没有出现。

**Comment by beyondliu** [comment]
![image](https://user-images.githubusercontent.com/4599057/53061087-aa492e80-34f7-11e9-80da-d2c55b79e99c.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/53223891-d1496100-36ad-11e9-93ef-bdb0d926ddcd.png)

上图是排序规则，之所以会出现点赞为0 排在有赞数大于0的前面，是因为统计的这一周里，该项目没有点赞数，而更新时间又排在后面。

**Comment by beyondliu** [comment]
同[issue20](https://github.com/tatfook/Paraworld-Feedback/issues/20), 用户从UI上看不到这个数字，多少会有些困惑。

**Comment by azothli** [comment]
按照设计，这个数值不显示
