### ISSUE TITLE
keepwork热门的排序

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#20]
排序的结果没有按从左到右从上到下展示？
![image](https://user-images.githubusercontent.com/4599057/53061377-7cb0b500-34f8-11e9-9aca-f35f39415f35.png)

**Comment by Sandu1213** [comment]
排序的结果是按照从左到右，再从上到下，依次排列的。
![image](https://user-images.githubusercontent.com/21214285/53224211-ec68a080-36ae-11e9-8d16-f10673ab477b.png)

**Comment by beyondliu** [comment]
这个last visit数值从UI上看不到，就会造成一定困惑，这个热门到底是按哪个数值排的，是不是排乱了。这个多少是个体验的问题。
