### ISSUE TITLE
keepwork探索的最新排序和综合排序的结果是一样的？

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#21]
![image](https://user-images.githubusercontent.com/4599057/53061627-1e380680-34f9-11e9-857e-289e6b16fbd8.png)
![image](https://user-images.githubusercontent.com/4599057/53061637-2db74f80-34f9-11e9-8feb-93c619392df8.png)

**Comment by Sandu1213** [comment]
综合排序与最新排序的结果应该是不一致的，但由于现在综合排序实际没有做，所以看到的排序结果是一样的。
综合排序问题由 issue [3557](https://github.com/tatfook/keepwork/issues/3557)在跟进，请稍后再查看

**Comment by azothli** [comment]
有专用的issue了，这个关闭
