### ISSUE TITLE
项目主页上成员不能点击

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#23]
![image](https://user-images.githubusercontent.com/4599057/53063820-7f170d00-3500-11e9-81fb-0bf0a0094811.png)
感觉如果可以点击的话会好些吧。

**Comment by Sandu1213** [comment]
建议可以点击，可以快速查看其它成员的信息

**Comment by azothli** [comment]
同意，可新窗口打开该成员的个人首页。

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #4177](https://github.com/tatfook/keepwork/issues/4177) via [**ZenHub**](https://www.zenhub.com/)
