### ISSUE TITLE
kw editor里面的mod编辑改名字时，如公司名时必须额外打几个字后才能删原有默认的字。

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#3]

**Comment by azothli** [comment]
@Kvaya  优化交互

**Comment by Kvaya** [comment]
使用场景：
培训班的小孩子对editor 中一些mod属性进行编辑时，用回格键删掉默认数值，但操作后不成功

解决方案：
允许用户使用回格键删掉默认数值，添加自定义数值。假设未添加，还是默认数值；
现editor mod一些属性支持回格键操作成功的情况如下：
![image](https://user-images.githubusercontent.com/39363297/51828885-83983d80-2327-11e9-8b2a-074b363970ac.png)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #3728](https://github.com/tatfook/keepwork/issues/3728) via [**ZenHub**](https://www.zenhub.com/)
