### ISSUE TITLE
好的作品的呈现

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#30]
很多人来到我们网站，就是想看到paracraft能够做出什么样的作品，是否足够好玩，是否能做很复杂的东西等等。但是现在推荐的是项目，打开后要下载软件才能看到，对于想快速了解我们的人并不是很方便。视频的呈现是比较方便的，可以考虑在“关于”页面里，就加上推荐作品视频的链接。

**Comment by beyondliu** [comment]
另外，希望我们首页上展示出来的作品真的要是我们最好的作品，能够充分展示paracraft的作品，让访问者看了后对paracraft产生好感，知道paracraft能够做出什么样的作品出来。

所以，“精选项目”应该是编辑选则的吧，这部分一定要是精选。其他的，如热门，推荐，排行榜里的作品，也尽量要把我们好的作品呈现出来，可以考虑从几个方面去分别呈现，比如热门可能就是属于老百姓喜闻乐见的，推荐就是比较阳春白雪高质量的等等。

**Comment by azothli** [comment]
这里面是几个问题：
1.keepwork是paracraft的用户社群网站，这里汇聚的应该是paracraft的用户，所以软件安装不是问题。

2.视频展示之类的是在paracraft产品官网（对用户介绍，吸引用户使用）

3.关于首页列表展示，精选为我们运营指定  其他都是针对指定规则生成的，目前效果不明显主要是用户数据过少导致的。
