### ISSUE TITLE
Keepwork网站整体呈现

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#31]
需要让几个主要的角色（stakeholders）来到我们网站，可以比较快的找到其所需的信息，比如学生，教师，机构，合作方。我在issue25(https://github.com/tatfook/Paraworld-Feedback/issues/25 )里的评论里已经讲了这里再单独做个issue。

**Comment by azothli** [comment]
网站定位有调整，设计中整体考虑，这个issue先关掉了
