### ISSUE TITLE
显示最近的几个版本并允许覆盖当前版本

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#33]
可以考虑做个简单的版本功能，即显示最近的几个版本，并允许选择某个旧版本生成最新版本。否则，现在的版本功能用户很难使用。经常在另一个电脑浏览器里打开的内容不知道不是最新的，编辑保存后就覆盖了服务器上的最新内容。尤其是有时候在另一台电脑上一下编辑了好几个文件，又回到先去的电脑上继续编辑的时候，要记住编辑了哪些文件然后一个个的更新到服务器的最新版本，确实挺麻烦。

**Comment by azothli** [comment]
这个已有设计，排计划中

**Comment by LiXizhi** [comment]
做好能显示下文档上次编辑的时间，参考github

**Comment by azothli** [comment]
已上线
