### ISSUE TITLE
没有写权限的markdown文档也可以查看markdown源码

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#34]
以前的keepwork，我记得没有写权限的markdown文档也可以在keepwork editor里打开的，只是无法编辑而已。现在keepwork好像不能这样了。很多时候需要拷贝他人的markdown源码（并不是写同一个文档），就很不方便。是否需要提供这个功能，需要考虑哪些方面，请综合考虑一下。

**Comment by beyondliu** [comment]
发现可以直接在url里加/ed/就可以看了。不过还是可以考虑一下要否在UI上给个编辑或查看按钮

**Comment by azothli** [comment]
页面有【查看代码】这个功能，你点一下就在编辑器里面打开代码了

**Comment by azothli** [comment]
上传不了图片，页面右上角的眼睛
