### ISSUE TITLE
课程的提示模块莫名其妙在输入的时候会突然消失

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#36]
![image](https://user-images.githubusercontent.com/4599057/54990921-cd836400-4ff6-11e9-8c40-bdfdd9a5d092.png)

**Comment by azothli** [comment]
Issue moved to [tatfook/keepwork #4560](https://github.com/tatfook/keepwork/issues/4560) via [**ZenHub**](https://www.zenhub.com/)
