### ISSUE TITLE
某些模块，如项目，quiz等，插入时并没有插入先前光标位置，而是总是插入到文档的最前面。

### ISSUE THREAD

**Issue by beyondliu** [tatfook/Paraworld-Feedback#9]

**Comment by Kvaya** [comment]
假设在代码区能识别当前光标位置，新增mod直接插入在当前光标位置；
假设在代码区不能识别当前光标位置，新增所有的mod依顺序放在文档的后面

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #3741](https://github.com/tatfook/keepwork/issues/3741) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #3742](https://github.com/tatfook/keepwork/issues/3742) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #3744](https://github.com/tatfook/keepwork/issues/3744) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Kvaya** [comment]
Issue moved to [tatfook/keepwork #3743](https://github.com/tatfook/keepwork/issues/3743) via [**ZenHub**](https://www.zenhub.com/)
